## Conformational Selection using Recursive Feature Elimination

In [1]:
import pandas as pd
import numpy as np
import sys

### Load the data

In [2]:
file_name = './df_DkSc_results_COCRYS_DEKOIS_DUD.pkl'
X_merged_dksc = pd.read_pickle(file_name)
# Extract activity column
y_true_merged = X_merged_dksc['activity']
# Drop column from merged_dkksc
X_merged_dksc = X_merged_dksc.drop('activity', axis=1)
X_merged_dksc.shape

(5839, 136)

#### Function and data to perform Scaffold Train-Test splitting

In [3]:
from scaffold_splitter import train_test_scaffold_split

# Compute or load the dataframe containing the Generic Murcko Scaffolds
file = './df_COCRYS_DUD_DEKOIS_Murcko_Scaffolds_SMILES.pkl'

df_scff_murcko = pd.read_pickle(file)

### Funtion to perform RFE with cross Validation

In [4]:
from sklearn.feature_selection import RFECV
from functools import wraps
import joblib
import os

def _run_RFECV(estimator, X_train, y_train, cv=5, scoring='roc_auc', 
                  filename=None, **kwargs):
    '''Simply runs a RFECV procedure'''
    # Intance and fit the rfe selector
    selector = RFECV(estimator,  cv = cv,
                     scoring = scoring, **kwargs)
    
    selector = selector.fit(X_train, y_train)
    return selector

def get_selected_features_per_step(fitted_selector, X):
    # Get the features ranking
    df_ = pd.DataFrame({'pdb_id': X.columns, 'rfe_ranking': fitted_selector.ranking_})
    # Sort features by ranking
    df_.sort_values('rfe_ranking', inplace = True)
    # Create a list of ranked features from size 1 to n
    list_of_confs_per_k = [ df_.index[:i+1].tolist() for i in range(len(df_))]
    # Create a dataframe indicating which features belong to a k subset
    df_confs_per_k = pd.DataFrame({'list_of_confs_rfe': list_of_confs_per_k})
    return df_confs_per_k
        
def REFCV_wrapper(estimator, X_train, y_train, filename, 
                  cv=5, scoring='roc_auc', **kwargs):
    if os.path.isfile(filename):
        # Load estimator from disk
        estimator = joblib.load(filename)
    else:
        estimator = _run_RFECV(estimator, X_train, y_train, cv=5, scoring='roc_auc', 
                    filename=None, **kwargs)
        # save to disk
        dump(estimator, filename)
    return estimator


In [5]:
from sklearn.model_selection import train_test_split
from scaffold_splitter import train_test_scaffold_split
from sklearn.metrics import roc_auc_score

#### Define X and y

In [6]:
# Train and test sets
X = X_merged_dksc
y = y_true_merged

## Random Splitting

#### RANDOM split: Logistic Regression as  estimator

In [7]:
%%time
from sklearn.linear_model import LogisticRegression

# RFECV object to be save 
dataset = 'MERGED'
model_name = 'LogReg'
split = 'random'
filename = f'./ml_models/RFECV_selector_{model_name}_{dataset}_{split}_split.joblib'
# Base Estimator Parameters
hyparams = {'C': 1.0, 'penalty': 'l1', 'solver': 'liblinear', 'max_iter': 150}
estimator = LogisticRegression(**hyparams)

#*********************************************************************************
# Do the RANDOM splitting
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, stratify=y)

#*********************************************************************************
# Run RFE
selector = REFCV_wrapper(estimator, X_train, y_train, 
                         filename=filename,
                         cv=5, step=1, min_features_to_select=1, n_jobs=4)

selector.grid_scores_

CPU times: user 6.78 ms, sys: 23.9 ms, total: 30.7 ms
Wall time: 45.4 ms


array([0.62716433, 0.64917252, 0.68705849, 0.70946982, 0.72798752,
       0.73703063, 0.75010978, 0.75391707, 0.7597195 , 0.76207597,
       0.76611985, 0.77098865, 0.77256657, 0.77546558, 0.77558032,
       0.77879425, 0.77893427, 0.77867573, 0.78100244, 0.78564726,
       0.79028027, 0.79185206, 0.7928754 , 0.7916826 , 0.79488738,
       0.79490302, 0.79831524, 0.80043408, 0.80380874, 0.80172766,
       0.80036368, 0.80193767, 0.80491196, 0.80604662, 0.80752347,
       0.80795042, 0.80722439, 0.81157952, 0.81014592, 0.81078167,
       0.80964124, 0.81018151, 0.81324093, 0.81332715, 0.81592818,
       0.81697687, 0.81698715, 0.81639278, 0.8165272 , 0.81550482,
       0.81755424, 0.8192236 , 0.81942178, 0.82023568, 0.82015542,
       0.81967402, 0.81977549, 0.81951307, 0.81944866, 0.81996167,
       0.82074363, 0.82058367, 0.82022013, 0.81987756, 0.81927803,
       0.81829346, 0.81631373, 0.81592847, 0.81612072, 0.8160681 ,
       0.8159877 , 0.81706812, 0.81692374, 0.81689676, 0.81770

#### RANDOM split: Random Forest as estimator 

In [8]:
%%time
from sklearn.ensemble import RandomForestClassifier

# RFECV object to be save 
dataset = 'MERGED'
model_name = 'RandomForest'
split = 'random'
filename = f'./ml_models/RFECV_selector_{model_name}_{dataset}_{split}_split.joblib'
# Base Estimator Parameters
hyparams = {'max_depth': 3, 'max_features': 'sqrt', 'min_samples_leaf': 0.02, 
            'min_samples_split': 0.1, 'n_estimators': 300}
estimator = RandomForestClassifier(**hyparams)

#*********************************************************************************
# Do the RANDOM splitting
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, stratify=y)

#*********************************************************************************
# Run RFE
selector = REFCV_wrapper(estimator, X_train, y_train, 
                         filename=filename,
                         cv=5, step=1, min_features_to_select=1, n_jobs=4)

selector.grid_scores_

CPU times: user 161 ms, sys: 45.5 ms, total: 206 ms
Wall time: 705 ms


array([0.62162938, 0.65026532, 0.67076128, 0.68358933, 0.69063308,
       0.69003071, 0.68722534, 0.6847175 , 0.6916404 , 0.68892701,
       0.6939982 , 0.6887191 , 0.69079222, 0.69588365, 0.69989284,
       0.69272027, 0.69132254, 0.69411384, 0.69442672, 0.69711989,
       0.69998961, 0.69904959, 0.70177686, 0.71333259, 0.71979928,
       0.71709107, 0.71765412, 0.71564549, 0.71701569, 0.71579763,
       0.71542242, 0.70942005, 0.71414999, 0.71676568, 0.7194116 ,
       0.72093381, 0.71718109, 0.72045262, 0.72412868, 0.72327514,
       0.72275183, 0.72583965, 0.72475638, 0.71957354, 0.72194132,
       0.72599916, 0.72027309, 0.7235409 , 0.72726664, 0.72178422,
       0.72548711, 0.72107662, 0.72435686, 0.72535318, 0.72448509,
       0.71792283, 0.7264301 , 0.71945912, 0.71931517, 0.72387675,
       0.72053676, 0.71937464, 0.7213415 , 0.7212305 , 0.72084919,
       0.72190177, 0.72120617, 0.72130748, 0.72195972, 0.7167877 ,
       0.71623688, 0.71961457, 0.7207135 , 0.71901609, 0.71933

## Scaffold Splitting

#### Define X and y

In [10]:
# Train and test sets
X = X_merged_dksc
y = y_true_merged
scaffold_series = df_scff_murcko['scff_generic']

#### SCAFFOLD split: Logistic Regression as  estimator

In [11]:
%%time
from sklearn.linear_model import LogisticRegression

# RFECV object to be save 
dataset = 'MERGED'
model_name = 'LogReg'
split = 'scaffold'
filename = f'./ml_models/RFECV_selector_{model_name}_{dataset}_{split}_split.joblib'
# Base Estimator Parameters
hyparams = {'C': 0.1, 'penalty': 'l2', 'solver': 'liblinear', 'max_iter': 150}
estimator = LogisticRegression(**hyparams)

#*********************************************************************************
# Do the RANDOM splitting
X_train, X_test, y_train, y_test = train_test_scaffold_split(X, y, 
                                    scaffold_series = scaffold_series,
                                    test_size=0.25, stratify=y)

#*********************************************************************************
# Run RFE
selector = REFCV_wrapper(estimator, X_train, y_train, 
                         filename=filename,
                         cv=5, step=1, min_features_to_select=1, n_jobs=4)
selector.grid_scores_

CPU times: user 109 ms, sys: 21.7 ms, total: 131 ms
Wall time: 143 ms


array([0.49886833, 0.66737057, 0.73512974, 0.71916561, 0.71157099,
       0.73900114, 0.75112039, 0.7657306 , 0.74857506, 0.75519763,
       0.76132298, 0.764079  , 0.76734636, 0.76845371, 0.77687793,
       0.78283805, 0.78433692, 0.78575497, 0.78525819, 0.78173585,
       0.79223336, 0.79599558, 0.79867117, 0.80133627, 0.79981548,
       0.80244103, 0.80662109, 0.80942533, 0.80946471, 0.80771876,
       0.80904132, 0.81202719, 0.81207761, 0.81258691, 0.80938028,
       0.8105278 , 0.80966137, 0.80654554, 0.80792053, 0.81198717,
       0.81173834, 0.81375687, 0.81374523, 0.81543712, 0.81658536,
       0.81574802, 0.81444894, 0.81378739, 0.81284256, 0.81469137,
       0.81418891, 0.81357732, 0.8124063 , 0.81274562, 0.81305067,
       0.81458274, 0.81599141, 0.81689075, 0.81759136, 0.81678831,
       0.81643244, 0.8186383 , 0.81812948, 0.81863231, 0.81966706,
       0.81837235, 0.81908503, 0.82052677, 0.82133014, 0.82028409,
       0.81954838, 0.81985419, 0.82064036, 0.82062331, 0.81843

#### SCAFFOLD split: Random Forest as estimator 

In [12]:
%%time
from sklearn.ensemble import RandomForestClassifier

# RFECV object to be save 
dataset = 'MERGED'
model_name = 'RandomForest'
split = 'scaffold'
filename = f'./ml_models/RFECV_selector_{model_name}_{dataset}_{split}_split.joblib'
# Base Estimator Parameters
hyparams = {'max_depth': 3, 'max_features': 'sqrt', 'min_samples_leaf': 0.02, 
            'min_samples_split': 0.1, 'n_estimators': 400}
estimator = RandomForestClassifier(**hyparams)

#*********************************************************************************
# Do the SCAFFOLD splitting
X_train, X_test, y_train, y_test = train_test_scaffold_split(X, y, 
                                    scaffold_series = scaffold_series,
                                    test_size=0.25, stratify=y)

#*********************************************************************************
# Run RFE
selector = REFCV_wrapper(estimator, X_train, y_train, 
                         filename=filename,
                         cv=5, step=1, min_features_to_select=1, n_jobs=4)
selector.grid_scores_

CPU times: user 285 ms, sys: 586 µs, total: 286 ms
Wall time: 334 ms


array([0.62807247, 0.65434801, 0.68180049, 0.71914251, 0.70185898,
       0.70949886, 0.71749916, 0.7168106 , 0.71777319, 0.73021456,
       0.73064559, 0.73845956, 0.73222367, 0.73472117, 0.73014669,
       0.7303391 , 0.73304695, 0.73231804, 0.73266971, 0.7320845 ,
       0.73012843, 0.73215795, 0.73131385, 0.74233804, 0.74040013,
       0.74264437, 0.73952067, 0.74240573, 0.74052518, 0.7428915 ,
       0.74201735, 0.74108235, 0.73729055, 0.7396859 , 0.74209018,
       0.74045662, 0.73914572, 0.73733552, 0.73797667, 0.7341799 ,
       0.73532397, 0.73809966, 0.74164115, 0.73717583, 0.73732063,
       0.73850945, 0.74305161, 0.74007098, 0.73950101, 0.73785406,
       0.73780903, 0.73992409, 0.7355391 , 0.74218836, 0.74176609,
       0.73612555, 0.7408378 , 0.74455828, 0.73729774, 0.73457117,
       0.73558999, 0.74013687, 0.73814917, 0.74163249, 0.73870498,
       0.73937818, 0.74002351, 0.74002363, 0.73821912, 0.73507202,
       0.73543098, 0.74156108, 0.7385141 , 0.74026242, 0.73733

In [76]:
# Get the features ranking
df_ = pd.DataFrame({'pdb_id': X.columns, 'rfe_ranking': selector.ranking_})
# Sort features by ranking
df_.sort_values('rfe_ranking', inplace = True)
#
list_of_confs_per_k = [ df_.index[:i+1].tolist() for i in range(len(df_))]
df_confs_per_k = pd.DataFrame({'list_of_confs_rfe': list_of_confs_per_k})
df_confs_per_k

list_of_confs_rfe
0                                                 [32]
1                                            [32, 113]
2                                        [32, 113, 73]
3                                    [32, 113, 73, 31]
4                                [32, 113, 73, 31, 98]
..                                                 ...
131  [32, 113, 73, 31, 98, 33, 34, 58, 36, 37, 92, ...
132  [32, 113, 73, 31, 98, 33, 34, 58, 36, 37, 92, ...
133  [32, 113, 73, 31, 98, 33, 34, 58, 36, 37, 92, ...
134  [32, 113, 73, 31, 98, 33, 34, 58, 36, 37, 92, ...
135  [32, 113, 73, 31, 98, 33, 34, 58, 36, 37, 92, ...

[136 rows x 1 columns]